---
apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
  labels:
    env: dev
    ver: "v1"
spec:
  containers:
    - name: my-container
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata: 
  name: qa-pod
  labels:
    env: prod
    ver: "v2"
spec:
  containers:
    - name: my-container
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP
---          


# kubectl apply -f .
# kubectl get pod -l env=prod
# kubectl get pod -l env=dev
# kubectl get pod -l "env in (dev), ver in (v1)"