apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: db-con
      image: mysql
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: aws
        - name: MYSQL_USER
          value: devops
        - name: MYSQL_PASSWORD
          value: devops123

# kubectl apply -f .
# kubectl get pod -w
# kubectl exec -it db-pod --bash
# mysql -u username -p
# enter password
